# ./docker-compose.yml
version: '3'

services:
  atenea-flask:
    build: .
    container_name: atenea-flask
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=atenea.vm
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - .:/var/www

  flask-test-nginx:
    image: jwilder/nginx-proxy
    container_name: flask-test-nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  elasticsearch:
    container_name: risk-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "5601:5601"

  risk-databases:
    image: mysql:5.7
    container_name: risk-databases
    hostname: risk-databases
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  risk-dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
