# ./docker-compose.yml
version: '3'

services:
  league-api:
    build: .
    container_name: league-api
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=league-api.vm
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - .:/var/www

  flask-test-nginx:
    image: jwilder/nginx-proxy
    container_name: flask-test-nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  databases:
    image: mysql:5.7
    container_name: mysql-databases
    hostname: mysql-databases
    environment:
    - MYSQL_USER=root
    - MYSQL_ROOT_PASSWORD=root
    ports:
    - 3306:3306
      
